# Generated by Django 3.1.4 on 2021-02-13 11:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of last update')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('liked_by', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of last update')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
